config/routes.rb
Concierge::Application.routes.draw do

  resources :favorites

  resources :votes

  resources :users
  resources :sessions

  root :to => "HomePage#index"
  match "index" => "HomePage#index"
  match "posterbackground" => "HomePage#poster"
  match "search" => "Search#search", :defaults => { :format => :xml}
  match "searchrecord/:service/:method/:id" =>"ServiceForward#recordrequest", :as => "searchrecord", :defaults => { :format => :xml}
  match "servicelinks" => "HomePage#serviceLinks", :defaults => { :format => :xml}
  match "services/:service/search" => "Search#servicesearch", :defaults => { :format => :xml}
  match "services/:service/index" => "ServiceForward#homepagerequest", :defaults => { :format => :xml}
  match "services/:service/:method" => "ServiceForward#listrequest", :defaults => { :format => :xml}
  match "services/:service/:method/:id" => "ServiceForward#recordrequest", :defaults => { :format => :xml}
  match "directrecord/:service/:id" => "ServiceForward#recordrequest", :defaults => { :format => :xml}

  match "admin" => "BackOffice#new"
  match "admin/create" => "BackOffice#create"
  match "admin/newservice" => "BackOffice#newservice"
  match "admin/createservice" => "BackOffice#createservice"
  match "admin/uploadfile" => "BackOffice#uploadFile"
  match "admin/listservices" => "BackOffice#listservices"
  match "admin/destroyservice" => "BackOffice#destroyservice"
  match "admin/destroyuser" => "BackOffice#destroyuser"
  match "admin/destroyfavourite" => "BackOffice#destroyfavourite"

  match "login" => "sessions#new"
  match "logout" => "sessions#destroy"
  match "register" => "users#new"
  match "activation" => "users#activate"
  match "history" => "Users#history", :defaults => { :format => :xml}
  match "favourites" => "Users#favourites", :defaults => { :format => :xml}
  match "options" => "Users#options"
  match "editfavourites" => "Users#editfavourites", :defaults => { :format => :xml}
  match "manageaccount" => "Users#manageaccount"
  match "update" => "Users#update"
  match "sendresource" => "Users#sendresource", :defaults => { :format => :xml}
  match "rateservice" => "Users#rateservice", :defaults => { :format => :xml}
  match "addfavourite" => "Users#addfavourite", :defaults => { :format => :xml}
  match "destroyfavorite" => "Users#destroyfavourite", :defaults => { :format => :xml}

end

app/models/competence.rb
class Competence < ActiveRecord::Base

     belongs_to :service

end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
  def self.save(upload)
      name =  upload['datafile'].original_filename
      directory = "public/data"
      # create the file path
      path = File.join(directory, name)
      # write the file
      File.open(path, "wb") { |f|
        f.write(upload['datafile'].read)
      }
    end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

  belongs_to :user

end

app/models/history.rb
class History < ActiveRecord::Base

  belongs_to :user

end

app/models/inf_entity.rb
class InfEntity < ActiveRecord::Base

  belongs_to :service

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/ref_entity.rb
class RefEntity < ActiveRecord::Base

  belongs_to :service

end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :infEntities
  has_many :refEntities
  has_many :tags
  has_many :competences
  has_many :votes

  has_attached_file :icon,
                    :url => "images/buttons/:basename.:extension",
                    :path => ":rails_root/public/images/buttons/:basename.:extension"
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  belongs_to :service

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :histories
  has_many :favorites
  has_many :votes

  attr_accessible :userName, :email, :password, :password_confirmationt

    attr_accessor :password
    before_save :encrypt_password

    validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :userName
    validates_uniqueness_of :userName
    validates_presence_of :email
    validates_uniqueness_of :email

    def self.authenticate(username, password)
      user = find_by_userName(username)
      if user && user.passwordHash == BCrypt::Engine.hash_secret(password, user.passwordSalt)
        user
      else
        nil
      end
    end

    def encrypt_password
      if password.present?
        self.passwordSalt = BCrypt::Engine.generate_salt
        self.passwordHash = BCrypt::Engine.hash_secret(password, passwordSalt)
      end
    end

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :service
  belongs_to :user

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # GET /favorites
  # GET /favorites.xml
  def index
    @favorites = Favorite.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @favorites }
    end
  end

  # GET /favorites/1
  # GET /favorites/1.xml
  def show
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/new
  # GET /favorites/new.xml
  def new
    @favorite = Favorite.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @favorite }
    end
  end

  # GET /favorites/1/edit
  def edit
    @favorite = Favorite.find(params[:id])
  end

  # POST /favorites
  # POST /favorites.xml
  def create
    @favorite = Favorite.new(params[:favorite])

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to(@favorite, :notice => 'Favorite was successfully created.') }
        format.xml  { render :xml => @favorite, :status => :created, :location => @favorite }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /favorites/1
  # PUT /favorites/1.xml
  def update
    @favorite = Favorite.find(params[:id])

    respond_to do |format|
      if @favorite.update_attributes(params[:favorite])
        format.html { redirect_to(@favorite, :notice => 'Favorite was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @favorite.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.xml
  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to(favorites_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/record_helper.rb
module RecordHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/test_parse_helper.rb
module TestParseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<h1>Listing favorites</h1>

<table>
  <tr>
    <th>User</th>
    <th>Url</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <td><%= favorite.user_id %></td>
    <td><%= favorite.url %></td>
    <td><%= favorite.title %></td>
    <td><%= link_to 'Show', favorite %></td>
    <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
    <td><%= link_to 'Destroy', favorite, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @favorite.user_id %>
</p>

<p>
  <b>Url:</b>
  <%= @favorite.url %>
</p>

<p>
  <b>Title:</b>
  <%= @favorite.title %>
</p>


<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>